plugins:
  docuss_enabled:
    refresh: true
    client: true
    default: false
  docuss_website_json_file:
    refresh: true
    client: true
    type: list
    default: ''
  docuss_hide_sugg_topics:
    refresh: true
    client: true
    default: false
  docuss_hide_categories:
    refresh: true
    client: true
    default: false
  docuss_hide_tags:
    refresh: true
    client: true
    default: false
  docuss_hide_hamburger_menu:
    refresh: true
    client: true
    default: false
